MusicBasket/MusicBasket/Controllers/ChartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicSpace.Domain;
using MusicSpace.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicSpace.Controllers
{
    public class ChartController : Controller
    {
        private readonly DataManager dataManager;
        public ChartController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public async Task<IActionResult> Index()
        {
            var weeklyCharts = await dataManager.WeeklyCharts.GetWeeklyCharts().ToListAsync();
            foreach(var wc in weeklyCharts)
            {
                wc.ChartSongs = await dataManager.ChartSongs.GetChartSongsByChartId(wc.Id).ToListAsync();
                foreach(var cs in wc.ChartSongs)
                {
                    cs.Song = await dataManager.Songs.GetSongById(cs.SongId);
                    cs.Song.SongPerformers = await dataManager.SongPerformers.GetSongPerformersBySongId(cs.SongId).ToListAsync();
                    foreach(var p in cs.Song.SongPerformers)
                    {
                        p.Performer = await dataManager.Performers.GetPerformerById(p.PerformerId);
                    }
                }
            }
            return View(weeklyCharts);
        }
    }
}

MusicBasket/MusicBasket/Views/Shared/CssPartial.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" asp-append-version="true">
<link rel="stylesheet" href="~/css/main.css" type="text/css" asp-append-version="true" />

MusicBasket/MusicBasket/Views/Shared/FooterPartial.cshtml
<div id="footer">
    <div>
    </div>
</div>

MusicBasket/MusicBasket/Views/Shared/HeaderPartial.cshtml
<header class="header">
    <div class="container">
        <div class="header__body">
            <div class="header__title">
                <a href="/" class="header__logo">
                    <img src="~/images/logo.png" alt="" />
                </a>
                <h1>@Config.ProjectName</h1>
            </div>
            <div class="header__burger">
                <span></span>
            </div>
            <nav class="navbar navbar-dark bg-dark header__menu">
                <ul class="header__list">
                    <li>
                        <a href="/" class="header__link">Home</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Chart" asp-action="Index" class="header__link">Charts</a>
                    </li>
                    <li>
                        <a href="/" class="header__link">Contacts</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a asp-area="User" asp-controller="Home" asp-action="Index" class="header__link">@User.Identity.Name</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a asp-area="" asp-controller="Account" asp-action="Login" class="header__link">Log In</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Account" asp-action="Registration" class="header__link">Sign Up</a>
                        </li>
                    }
                </ul>
            </nav>
        </div>
    </div>
</header>

MusicBasket/MusicBasket/Views/Shared/MetatagsPartial.cshtml
@using MusicSpace.Service
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.ProjectName</title>
}
@if (ViewBag.Description != null)
{ 
    <meta name="description" content="@ViewBag.Description"/>
}
@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords"/>
}

MusicBasket/MusicBasket/Views/Shared/ScriptsPartial.cshtml
<!--Подключаем файл JS со скриптами-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>$(document).ready(function () {
        function Contains(text_one, text_two) {
            if (text__one.indexOf(text__two) != -1)
                return true;
        }
        $("#Search".keyup(function () {
            var searchText = $("#Search").val().toLowerCase();
            $(".Search").each(function () {
                if (!Contains($(this).text().toLowerCase(), searchText)) {
                    $(this).hide();
                }
                else {
                    $(this).show();
                }
            })
        }))
    })</script>
<script src="~/js/main.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

MusicBasket/MusicBasket/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html translate="no">
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body>
    <div class="wrapper">

        @await Html.PartialAsync("HeaderPartial")

        <div class="content">
            <div class="container">
                @RenderBody()
            </div>
        </div>

        @await Html.PartialAsync("FooterPartial")

        <div id="player">
            <div class="container__primary">
                <div id="currentTime">
                    <p>0:00</p>
                </div>
                <div id="player__control__container">
                    <div id="song__info">
                        <div id="label">
                            <p>Текущая песня</p>
                        </div>
                        <div id="song__title">
                            <p>Не выбрана</p>
                        </div>
                        <div id="song__slider">
                            <div id="slider">
                                <input type="range" min="0" max="100" value="0"/>
                            </div>
                            <div id="volume__slider">

                            </div>
                        </div>
                    </div>
                </div>
                <div id="duration">
                    <p>0:00</p>
                </div>
            </div>
        </div>

    </div>
    @await Html.PartialAsync("ScriptsPartial")
</body>
</html>