MusicBasket/MusicBasket/Areas/Admin/Controllers/AlbumsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicSpace.Areas.Admin.Models;
using MusicSpace.Domain;
using MusicSpace.Domain.Entities;
using MusicSpace.Service.FileService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicSpace.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AlbumsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly FileService fileService;
        public AlbumsController(DataManager dataManager, IWebHostEnvironment env)
        {
            this.dataManager = dataManager;
            fileService = new FileService(env);
        }
        public async Task<IActionResult> Index()
        {
            List<Album> viewData = await dataManager.Albums.GetAlbums().OrderBy(e => e.ReleaseDate).ToListAsync();
            foreach(var item in viewData)
            {
                item.AlbumPerformers = await dataManager.AlbumPerformers.GetAlbumPerformersByAlbumId(item.Id).ToListAsync();
                foreach(var aPerformer in item.AlbumPerformers)
                {
                    aPerformer.Performer = await dataManager.Performers.GetPerformerById(aPerformer.PerformerId);
                }
            }
            return View(viewData);
        }

        public IActionResult Create()
        {
            AlbumCreateViewModel songCreateViewModel = new AlbumCreateViewModel()
            {
                Album = new Album() { Id = Guid.NewGuid().ToString() },
                Songs = dataManager.Songs.GetSongs(),
                Performers = dataManager.Performers.GetPerformers()
            };
            return View(songCreateViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Title,CoverFile,ReleaseDate")] Album album)
        {
            if (ModelState.IsValid)
            {
                album.Id = Guid.NewGuid().ToString();                
                album.CoverPath = fileService.Upload(album.CoverFile, FileType.Cover);
                dataManager.Albums.SaveAlbum(album);
                List<string> performerIDs = Request.Form["Performers"].ToString().Split(",").ToList();
                foreach (var performerId in performerIDs)
                {
                    dataManager.AlbumPerformers.SaveAlbumPerformer(
                        new AlbumPerformer()
                        { AlbumId = album.Id, PerformerId = performerId });
                }
                return RedirectToAction(nameof(Index));
            }
            AlbumCreateViewModel albumCreateViewModel = new AlbumCreateViewModel()
            {
                Album = new Album() { Id = Guid.NewGuid().ToString() },
                Songs = dataManager.Songs.GetSongs(),
                Performers = dataManager.Performers.GetPerformers()
            };
            return View(albumCreateViewModel);
        }
    }
}

MusicBasket/MusicBasket/Areas/Admin/Views/Albums/Create.cshtml
@model AlbumCreateViewModel

@{
    string strTitle = "Добавление альбома";
    ViewBag.Title = strTitle;
}
<a asp-area="Admin" asp-controller="Home" asp-action="Index">Панель администратора</a>
<form asp-area="Admin" asp-controller="Albums" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly">
    </div>
    <div>
        <label asp-for="Album.Title"></label>
        <input asp-for="Album.Title" />
        <span asp-validation-for="Album.Title"></span>
    </div>
    <div>
        <label asp-for="Album.CoverFile"></label>
        <input asp-for="Album.CoverFile" type="file" />
        <span asp-validation-for="Album.CoverFile"></span>
    </div>
    <div>
        <label asp-for="Album.ReleaseDate"></label>
        <input asp-for="Album.ReleaseDate" />
        <span asp-validation-for="Album.ReleaseDate"></span>
    </div>
    <div>
        <label asp-for="Performers"></label>
        <select id="Performers" asp-for="Performers" multiple>
            <option>Выберите исполнителей</option>
            @foreach (var item in Model.Performers)
            {
                <option value="@(item.Id)">
                    @Html.DisplayFor(perf => item.PerformerName)
                </option>
            }
        </select>
        <span asp-validation-for="Performers"></span>
    </div>
    <div>
        <input type="submit" value="Добавить" />
    </div>
</form>

MusicBasket/MusicBasket/Areas/Admin/Views/Albums/Index.cshtml
@model IEnumerable<Album>

@{
    string strTitle = "Список альбомов";
    ViewBag.Title = strTitle;
}
<a asp-area="Admin" asp-controller="Home" asp-action="Index">Панель администратора</a>
<a asp-area="Admin" asp-controller="Albums" asp-action="Create">Добавить</a>
<div class="table__container">
    <table>
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CoverPath)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AlbumPerformers)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ReleaseDate)
                </th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <img src="~/uploads/covers/@(Html.DisplayFor(modelItem => item.CoverPath))" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            <div>
                                @foreach (var songPerformers in item.AlbumPerformers)
                                {
                                    <span>@Html.DisplayFor(modelItem => songPerformers.Performer.PerformerName)</span>
                                }
                            </div>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ReleaseDate)
                        </td>
                        <td>
                            <div class="table__link">
                                <a asp-area="Admin" asp-controller="Albums" asp-action="Edit" asp-route-id="@item.Id">Изменить</a>
                                <a asp-area="Admin" asp-controller="Albums" asp-action="Details" asp-route-id="@item.Id">Подробнее</a>
                                <a asp-area="Admin" asp-controller="Albums" asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>