MusicBasket/MusicBasket/Areas/Admin/Controllers/ChartsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicSpace.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicSpace.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ChartsController : Controller
    {
        private readonly DataManager dataManager;
        public ChartsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        // GET: ChartsController
        public async Task<ActionResult> Index()
        {
            return View(await dataManager.WeeklyCharts.GetWeeklyCharts().ToListAsync());
        }

        // GET: ChartsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: WeeklyChartsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WeeklyChartsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: WeeklyChartsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: WeeklyChartsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: WeeklyChartsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: WeeklyChartsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MusicBasket/MusicBasket/Areas/Admin/Controllers/SongsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using MusicSpace.Areas.Admin.Models;
using MusicSpace.Domain;
using MusicSpace.Domain.Entities;
using MusicSpace.Service.FileService;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;

namespace MusicSpace.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SongsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly FileService fileService;
        public SongsController(DataManager dataManager, IWebHostEnvironment env)
        {
            this.dataManager = dataManager;
            fileService = new FileService(env);
        }
        public async Task<IActionResult> Index()
        {
            List<Song> viewData = await dataManager.Songs.GetSongs().ToListAsync();
            foreach (var item in viewData)
            {
                item.Album = dataManager.Albums.GetAlbumBySongId(item.Id);
                item.SongPerformers = await dataManager.SongPerformers.GetSongPerformersBySongId(item.Id).ToListAsync();
                foreach (var sPerformer in item.SongPerformers)
                {
                    sPerformer.Performer = await dataManager .Performers.GetPerformerById(sPerformer.PerformerId);
                }
            }
            return View(viewData);
        }

        public IActionResult Create()
        {
            SongCreateViewModel songCreateViewModel = new SongCreateViewModel()
            {
                Song = new Song() { Id = Guid.NewGuid().ToString() },
                Albums = dataManager.Albums.GetAlbums(),
                Performers = dataManager.Performers.GetPerformers()
            };
            return View(songCreateViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Title,CoverFile,SongFile,ReleaseDate")] Song song) 
        {
            if (ModelState.IsValid)
            {
                song.Id = Guid.NewGuid().ToString();
                song.AlbumId = Request.Form["Albums"].ToString();
                song.CoverPath = fileService.Upload(song.CoverFile, FileType.Cover);
                song.SongPath = fileService.Upload(song.SongFile, FileType.Song);
                dataManager.Songs.SaveSong(song);
                List<string> performersIDs = Request.Form["Performers"].ToString().Split(",").ToList();
                foreach (var performerId in performersIDs)
                {
                    dataManager.SongPerformers.SaveSongPerformer(
                        new SongPerformer() 
                        { SongId = song.Id, PerformerId = performerId });
                }
                return RedirectToAction(nameof(Index));
            }
            SongCreateViewModel songCreateViewModel = new SongCreateViewModel()
            {
                Song = new Song() { Id = Guid.NewGuid().ToString() },
                Albums = dataManager.Albums.GetAlbums(),
                Performers = dataManager.Performers.GetPerformers()
            };
            return View(songCreateViewModel);
        }
    }
}

MusicBasket/MusicBasket/Controllers/ChartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicSpace.Domain;
using MusicSpace.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicSpace.Controllers
{
    public class ChartController : Controller
    {
        private readonly DataManager dataManager;
        public ChartController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public async Task<IActionResult> Index()
        {
            var weeklyCharts = await dataManager.WeeklyCharts.GetWeeklyCharts().ToListAsync();
            foreach(var wc in weeklyCharts)
            {
                wc.ChartSongs = await dataManager.ChartSongs.GetChartSongsByChartId(wc.Id).ToListAsync();
                foreach(var cs in wc.ChartSongs)
                {
                    cs.Song = await dataManager.Songs.GetSongById(cs.SongId);
                    cs.Song.SongPerformers = await dataManager.SongPerformers.GetSongPerformersBySongId(cs.SongId).ToListAsync();
                    foreach(var p in cs.Song.SongPerformers)
                    {
                        p.Performer = await dataManager.Performers.GetPerformerById(p.PerformerId);
                    }
                }
            }
            return View(weeklyCharts);
        }
    }
}

MusicBasket/MusicBasket/Areas/Admin/Views/Charts/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MusicBasket/MusicBasket/Areas/Admin/Views/Charts/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MusicBasket/MusicBasket/Areas/Admin/Views/Charts/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MusicBasket/MusicBasket/Areas/Admin/Views/Charts/Index.cshtml
@model IEnumerable<WeeklyChart>

@{
    string strTitle = "Список недельных чартов";
    ViewBag.Title = strTitle;
}
<a asp-area="Admin" asp-controller="Home" asp-action="Index">Панель администратора</a>
<a asp-area="Admin" asp-controller="WeeklyChart" asp-action="Create">Добавить</a>
<div class="table__container">
    <table>
        <thead>
            <tr>
                <th>
                    № Чарта
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ReleaseDate)
                </th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                @for(int i = 0; i < Model.Count(); i++)
                {
                    <tr>
                        <td>
                            @(i+1)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.ElementAt(i).ReleaseDate)
                        </td>
                        <td>
                            <div class="table__link">
                                <a asp-area="Admin" asp-controller="Songs" asp-action="Edit" asp-route-id="Model.ElementAt(i).Id">Изменить</a>
                                <a asp-area="Admin" asp-controller="Songs" asp-action="Details" asp-route-id="Model.ElementAt(i).Id">Подробнее</a>
                                <a asp-area="Admin" asp-controller="Songs" asp-action="Delete" asp-route-id="Model.ElementAt(i).Id">Удалить</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>